title: "Meta EN|IX API"
description: "Official API documentation for Meta EN|IX."
theme: jekyll-theme-dinky

url: "https://nxfinity.github.io"
baseurl: "/enix_backend"

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
