title: "Meta EN|IX API"
description: "Official API documentation for Meta EN|IX."
#theme: jekyll-theme-dinky
remote_theme: pages-themes/merlot@v0.2.0

url: "https://nxfinity.github.io"
baseurl: "/enix_backend"

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
